import { EyeOutlined, EditTwoTone, InfoCircleTwoTone, DeleteTwoTone } from '@ant-design/icons';
import ViewAction from '../../../components/Actions/ViewAction';
import EditAction from '../../../components/Actions/EditAction';
import DeleteAction from '../../../components/Actions/DeleteAction';

export const ExampleAction = {
    COMMON_ACTION: {
        CREATE: {
            type: 'item',
            title: 'New Example',
            action: 'create',
            permission: 'auth:example:create',
            link: { to: '' },
            component: '',
            className: '',
            icon: <EyeOutlined />,
        },
        EDIT: {
            type: 'item',
            title: 'Edit Example',
            action: 'edit',
            permission: 'auth:example:edit',
            link: { to: '' },
            component: '',
            className: '',
            icon: <EditTwoTone />,
        },
        VIEW: {
            type: 'item',
            title: 'View Example',
            action: 'view',
            permission: 'auth:example:view',
            link: { to: '' },
            component: '',
            className: '',
            icon: <InfoCircleTwoTone />,
        },
        DELETE: {
            type: 'item',
            title: 'Delete Example',
            action: 'delete',
            permission: 'auth:example:delete',
            link: { to: '' },
            component: '',
            className: '',
            icon: <DeleteTwoTone />,
        },
        UPDATE_EXAMPLE_STATUS: {
            type: 'item',
            title: 'Update Status',
            action: 'edit',
            link: { to: '' },
            permission: 'auth:example:edit',
            component: '',
            className: '',
        },
    },
    LIST_ITEM_ACTION: [
        {
            type: 'item',
            title: 'View',
            action: 'active',
            permission: 'auth:example:view',
            link: { to: '' },
            component: ViewAction,
            className: 'ext-gray-900 bg-gray-100 me-2',
            icon: <InfoCircleTwoTone />,
        },
        {
            type: 'item',
            title: 'Edit',
            action: 'inactive',
            permission: 'auth:example:edit',
            link: { to: '' },
            component: EditAction,
            className: 'ext-gray-900 bg-gray-100 me-2',
            icon: <EditTwoTone />,
        },
        {
            type: 'item',
            title: 'Delete',
            action: 'delete',
            permission: 'auth:example:delete',
            link: { to: '' },
            component: DeleteAction,
            className: 'ext-gray-900 bg-gray-100 me-2',
            icon: <DeleteTwoTone />,
        },
    ],
    BULK_ACTION: {
        permission: 'auth:example:multiSelect',
        action_list: [
            {
                type: 'item',
                title: 'Mark as Active',
                action: 'active',
                link: { to: '' },
                component: '',
                className: 'grid-view-action',
                icon: <EyeOutlined />,
            },
            {
                type: 'item',
                title: 'Mark as Inactive',
                action: 'inactive',
                link: { to: '' },
                component: '',
                className: 'grid-view-action',
                icon: <EyeOutlined />,
            },
            {
                type: 'item',
                title: 'Delete',
                action: 'delete',
                permission: 'auth:example:delete',
                link: { to: '' },
                component: '',
                className: 'grid-view-action',
                icon: <EyeOutlined />,
            },
        ],
    },
};
